before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: SbCc4/RSbGNiI01275cydAILl1CyaIp5hpg2JteNo4Qqttv99AEyqJNz5MecEit9rRKNkzumZPgnj7AYEt9moxt6YPhxDpVxKP5Ihz4uAUKXgTysrVjCKEmmMelTwsnPSGe9uTVz9ZO+afIR8uRf1ZZNKQptFITqhp3rUpi4uK/2ECtj8/hvxNV+UJi5podJTaCewCypxE5CD8wYkkWznWAVxfgOMON8+v69wJOB43RF2FMH9oaqL0XqXW2BbqCh55GuvTOcy9BEHWj5Y8j5B277BeNMOEJ4V5IcV16nQe4B+HFHlf86aeCY+vs7d/fgpN2V5pQRM3YdhYCdseONtiSli2I04FicshKTvqC1AYz9AomQk2/ANXNr8hnDXOpELH7eGo7AkGb1MYdCDXP4Hpk3QTqKy3KOm2ffmN4HnmVeYMVoHgDAZXgE6HPkGPpzmFRutG4N9ZE9z38pzZk1qbrRH/35nxJlq+GV5u4IU9FONBU1IF7nOgd39gxYFq2yLx8Lg0BEbL/XxGA8lwBJyiJOvyVHBIpRjrqvhpT6dkYbCYcOGTFEJFM2EPqimd4JPzK1DKrP+QL48z5EoWZTNUWEYcuV6TXx8TtEOkRB8dChDKYuQZ76q3PrlvMFa20ffkfNvxFl2q4SHQcEnwENYaYMK6zdWnfowDRIukoaRzo= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
